# ROS ALL
#log4j.logger.ros=DEBUG
log4j.logger.ros=ALL

# ROS
log4j.logger.ros.rviz=INFO
log4j.logger.ros.roscpp=INFO
log4j.logger.ros.actionlib=INFO
log4j.logger.ros.interactive_markers=INFO
log4j.logger.ros.kdl_parser=INFO
log4j.logger.ros.urdf=INFO
log4j.logger.ros.robot_state_publisher=INFO

# CONSOLE BRIDGE
log4j.logger.ros.rosconsole_bridge=INFO
log4j.logger.ros.rosconsole_bridge.console_bridge=INFO
log4j.logger.ros.rosconsole_bridge.class_loader.class_loader_private=INFO
log4j.logger.ros.rosconsole_bridge.urdfdom=INFO

# ClassLoaders
log4j.logger.ros.rqt_gui_cpp.pluginlib.ClassLoader=INFO
log4j.logger.ros.image_transport.pluginlib.ClassLoader=INFO
log4j.logger.ros.image_transport.pluginlib.ClassLoader=INFO
log4j.logger.ros.nodelet.pluginlib.ClassLoader=INFO
log4j.logger.ros.gazebo_ros_control.pluginlib.ClassLoader=INFO
log4j.logger.ros.bin_picking.pluginlib.ClassLoader=INFO
log4j.logger.ros.robot_controllers_interface.pluginlib.ClassLoader=INFO
log4j.logger.ros.rosconsole_bridge.class_loader.ClassLoader=INFO
log4j.logger.ros.moveit_ros_move_group.pluginlib.ClassLoader=INFO
log4j.logger.ros.moveit_ros_planning.pluginlib.ClassLoader=INFO
log4j.logger.ros.moveit_setup_assistant.pluginlib.ClassLoader=INFO
log4j.logger.ros.hrp2jsknt_moveit_demos.pluginlib.ClassLoader=INFO

# Gazebo
log4j.logger.ros.hector_gazebo_plugins.gazebo_ros_imu=INFO

# MoveIt
log4j.logger.ros.moveit_core.robot_model=INFO
log4j.logger.ros.moveit_core.planning_scene=INFO
log4j.logger.ros.moveit_core.constraint_samplers=INFO
log4j.logger.ros.moveit_core.background_processing=INFO
log4j.logger.ros.moveit_ros_planning.planning_scene_monitor=INFO
log4j.logger.ros.moveit_ros_planning.kinematics_plugin_loader=INFO
log4j.logger.ros.moveit_ros_planning=INFO
log4j.logger.ros.moveit_ros_perception=INFO
log4j.logger.ros.moveit_fake_controller_manager=INFO
log4j.logger.ros.moveit_kinematics.kdl=INFO

# MoveIt Actionlib
log4j.logger.ros.moveit_ros_visualization.actionlib=INFO
log4j.logger.ros.moveit_ros_planning_interface.actionlib=INFO
log4j.logger.ros.moveit_ros_manipulation.actionlib=INFO
log4j.logger.ros.hrp2jsknt_moveit_demos.actionlib=INFO
log4j.logger.ros.moveit_ros_move_group.actionlib=INFO

# Navigation
log4j.logger.ros.navfn=INFO
log4j.logger.ros.costmap_2d=INFO
log4j.logger.ros.move_base.move_base_plan_thread=INFO
log4j.logger.ros.gmapping=INFO
log4j.logger.ros.ros.base_local_planner=INFO

# ROS Control
log4j.logger.ros.cartesian_controller=INFO
log4j.logger.ros.controller_manager=INFO
log4j.logger.ros.controller_manager.service=INFO
log4j.logger.ros.controller_manager.pluginlib=INFO
log4j.logger.ros.joint_trajectory_controller=INFO
log4j.logger.ros.joint_state_controller=INFO
log4j.logger.ros.control_toolbox.pid=INFO
log4j.logger.ros.ros_control_boilerplate.joint_positions=INFO
log4j.logger.ros.ros_control_boilerplate.generic_hw_interface=INFO
log4j.logger.ros.moveit_simple_controller_manager=WARN
log4j.logger.ros.moveit_simple_controller_manager.manager=WARN
log4j.logger.ros.moveit_ros_planning.traj_execution=WARN
log4j.logger.ros.moveit_ros_control_interface=INFO
log4j.logger.ros.diff_drive_controller.jackal_velocity_controller=INFO

# ROS Control actionlib
log4j.logger.ros.moveit_ros_control_interface.actionlib=INFO
log4j.logger.ros.moveit_simple_controller_manager.actionlib=INFO
log4j.logger.ros.ros_control_boilerplate.actionlib=INFO
log4j.logger.ros.joint_trajectory_controller.actionlib=INFO

# Visuals Tools Code
log4j.logger.ros.moveit_visual_tools=INFO
log4j.logger.ros.rviz_visual_tools.visual_tools=INFO
log4j.logger.ros.rviz_visual_tools.tf_visual_tools=INFO
log4j.logger.ros.ompl_visual_tools.moveit_viz_window=INFO

# PickNik Amazon Challenge
log4j.logger.ros.picknik_main.main=INFO
log4j.logger.ros.picknik_main.parser=INFO
log4j.logger.ros.picknik_main.shelf=INFO
log4j.logger.ros.picknik_main.collision_object=INFO
log4j.logger.ros.picknik_main.manipulation_data=INFO
log4j.logger.ros.picknik_main.product_simulator=INFO
log4j.logger.ros.picknik_main.planning_scene_manager=INFO
log4j.logger.ros.picknik_main.line_tracking=INFO
log4j.logger.ros.picknik_main.perception_interface.actionlib=INFO
log4j.logger.ros.picknik_main.perception_interface=INFO
log4j.logger.ros.picknik_perception.actionlib=INFO
log4j.logger.ros.picknik_main.perception_interface=INFO

# Grasping
log4j.logger.ros.moveit_grasps.grasp_generator=INFO
log4j.logger.ros.moveit_grasps.grasp_filter.superdebug=INFO
log4j.logger.ros.moveit_grasps.grasp_scorer=INFO
log4j.logger.ros.moveit_grasps.cuboid_grasp_points=INFO
log4j.logger.ros.moveit_grasps.cuboid=INFO
log4j.logger.ros.moveit_grasps.cuboid_axis_grasps=INFO
log4j.logger.ros.moveit_grasps.grasp_data=INFO
log4j.logger.ros.moveit_grasps.grasp_planner.waypoints=INFO
log4j.logger.ros.moveit_grasps.grasp_planner.lift_distance=INFO

# Manipulation - General
log4j.logger.ros.picknik_main.manipulation.superdebug=INFO
log4j.logger.ros.picknik_main.manipulation.end_effector=INFO
log4j.logger.ros.picknik_main.manipulation.interpolation=INFO

# JACO
log4j.logger.ros.kinova_driver.actionlib=INFO
log4j.logger.ros.kinova_driver.raw_position=INFO
log4j.logger.ros.kinova_driver.raw_velocity=INFO
log4j.logger.ros.kinova_driver.raw_effort=INFO

# JACO ros_control
log4j.logger.ros.kinova_ros_control.raw_positions=INFO
log4j.logger.ros.kinova_ros_control.raw_velocities=INFO
log4j.logger.ros.kinova_ros_control.raw_torques=INFO
log4j.logger.ros.kinova_ros_control.commanded_position=INFO
log4j.logger.ros.kinova_ros_control.commanded_velocity=INFO

# Perception
log4j.logger.ros.bounding_box.bounding_box=INFO

# OMPL Planning Stuff
#log4j.logger.ros.ompl=WARN
#log4j.logger.ros.moveit_ompl=WARN
#log4j.logger.ros.rosconsole_bridge.moveit_ompl=INFO
log4j.logger.ros.moveit_ompl.parameters=INFO

# moveit_planners
log4j.logger.ros.moveit_planners_ompl.parameters=INFO
log4j.logger.ros.moveit_planners_ompl.ompl=INFO

# moveit_boilerplate
# log4j.logger.ros.moveit_boilerplate.execution_interface=INFO
log4j.logger.ros.moveit_boilerplate.execution_interface.trajectory=INFO
log4j.logger.ros.moveit_boilerplate.execution_interface.file_path=INFO
log4j.logger.ros.moveit_boilerplate.actionlib=INFO

# rosparam shortcuts
log4j.logger.ros.rosparam_shortcuts=INFO

## Baxter
log4j.logger.ros.baxter_ikfast_left_arm_plugin.ikfast=INFO
log4j.logger.ros.baxter_sim_kinematics=INFO
log4j.logger.ros.gazebo_ros.api_plugin=INFO
log4j.logger.ros.gazebo_ros.api_plugin.xml=INFO
log4j.logger.ros.gazebo_ros.paths_plugin=INFO
log4j.logger.ros.baxter_sim_controllers=INFO
log4j.logger.ros.gazebo_ros_control=INFO
log4j.logger.ros.gazebo_plugins.block_laser=INFO

# Houston Mechatronics
log4j.logger.ros.industrial_robot_client.actionlib=INFO
log4j.logger.ros.industrial_robot_client=INFO
log4j.logger.ros.industrial_robot_client.joint_trajectory_action=INFO
log4j.logger.ros.industrial_trajectory_filters=INFO
log4j.logger.ros.smt_brz_motors.actionlib=INFO
log4j.logger.ros.smt_brz_ptu.actionlib=INFO
log4j.logger.ros.trac_ik_kinematics_plugin.trac_ik=INFO
log4j.logger.ros.trac_ik_kinematics_plugin=WARN

# Fetch simulation
log4j.logger.ros.robot_controllers.actionlib=INFO