#!/bin/bash
alias mynotes="cd $SCRIPT_BASE_PATH/notes/"
alias gitnotes="e $SCRIPT_BASE_PATH/notes/git.md"
alias hgnotes="e $SCRIPT_BASE_PATH/notes/hg.md"
alias ubuntunotes="cd $SCRIPT_BASE_PATH/notes/ && ls -l ubuntu_*"
alias emacsnotes="e $SCRIPT_BASE_PATH/notes/emacs.md"
alias brewnotes="e $SCRIPT_BASE_PATH/notes/brew.md"
alias moveitnotes="e $SCRIPT_BASE_PATH/notes/moveit.md"
alias gdbnotes="e $SCRIPT_BASE_PATH/notes/gdb.md"
alias rosnotes="e $SCRIPT_BASE_PATH/notes/ros.md"
alias baxternotes="e $SCRIPT_BASE_PATH/scripts/baxter.sh"
alias macnotes="e $SCRIPT_BASE_PATH/notes/mac.md"
alias bloomnotes="e $SCRIPT_BASE_PATH/notes/bloom.md"
alias eigennotes="e $SCRIPT_BASE_PATH/notes/eigen.md"
alias dockernotes="e $SCRIPT_BASE_PATH/notes/docker.md"
alias awsnotes="e $SCRIPT_BASE_PATH/notes/aws.md"
